enum EnvironmentEnum {
  dev,
  uat,
  prod,
  stage,
}

enum UrlEndPointEnum {
  login,
  createUser,
  logout,
  fetchUserProfile,
  verifyOtp,
  verifyResetOtp,
  resetPassword,
  forgotPassword,
  updateprofilepic,
  updateUserWithProfile,
  updateUser,
  updateUserExt,
  uploadImage,
  allDoctors,
  searchDoctor,
  specialties,
  doctorBySpecialty,
  doctorDetails,
  searchDoctors,
  userExtras,
  createInstantVisit,
  createAppointment,
  cancelAppointment,
  registerDeviceFCM,
  getTelemedSessions,
  availableSlots,
  abhipayPayment,
  medications,
  saveSession,
  updateSession,
  recentConsultations,
  validateCoupon,
  labReports,
  searchHistory,
  payments,
  contactUs,
  getSessionNote,
  getAppointments,
  personSearch,
}

enum FileType { profilepic, labreport, custom }
