// import 'package:flutter/material.dart';
// import 'package:url_launcher/url_launcher.dart';

// class StripeSandbox extends StatelessWidget {
//   const StripeSandbox({super.key});

//   // Payment Link generated by Stripe (use the actual link for testing)
//   final String paymentLink =
//       'https://buy.stripe.com/test_4gwaHjbeo2x46BOaEG'; // Replace with your actual payment link

//   // Launch the payment link
//   Future<void> _launchPaymentLink() async {
//     final uri = Uri.parse(paymentLink);
//     if (await canLaunchUrl(uri)) {
//       await launchUrl(uri, mode: LaunchMode.externalApplication);
//     } else {
//       throw 'Could not launch $paymentLink';
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: const Text('Stripe Sandbox')),
//       body: Center(
//         child: ElevatedButton(
//           onPressed: _launchPaymentLink,
//           child: const Text('Go to Payment Page'),
//         ),
//       ),
//     );
//   }
// }

import 'package:flutter/material.dart';
import 'package:virualapi/constants/constant.dart';
import 'package:webview_flutter/webview_flutter.dart';

class StripeSandbox extends StatefulWidget {
  const StripeSandbox({super.key});

  @override
  State<StripeSandbox> createState() => _StripeSandboxState();
}

class _StripeSandboxState extends State<StripeSandbox> {
  final String paymentUrl = 'https://buy.stripe.com/test_4gwaHjbeo2x46BOaEG';

  late final WebViewController _controller;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (progress) {
            setState(() => _isLoading = progress < 100);
          },
          onPageStarted: (url) {
            setState(() => _isLoading = true);
          },
          onPageFinished: (url) {
            setState(() => _isLoading = false);
          },
          onNavigationRequest: (request) {
            final url = request.url;

            if (url.contains('success')) {
              _showStatus('✅ Payment Successful');
              return NavigationDecision.prevent;
            } else if (url.contains('cancel') || url.contains('fail')) {
              _showStatus('❌ Payment Cancelled');
              return NavigationDecision.prevent;
            }

            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse(paymentUrl));
  }

  void _showStatus(String message) {
    ScaffoldMessenger.of(context)
        .showSnackBar(SnackBar(content: Text(message)));
    Navigator.pop(context); // close WebView page
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Stripe Payment'),
        backgroundColor: COLOR_PRIMARY,
      ),
      body: Stack(
        children: [
          WebViewWidget(controller: _controller),
          if (_isLoading) const Center(child: CircularProgressIndicator()),
        ],
      ),
    );
  }
}
